// gen-funcs-sigs reads the canonical per-function markdown docs
// under `docs/funcs/*.md` and emits `rts/signatures_gen.go` - the
// sorted list of public builtin signature strings the runtime
// loads at init.
//
// Pre-codegen, signatures lived twice: once in
// `rts/signatures.go` as Go literals, and once in
// `docs/funcs/<name>.md` under `## Signature`. A drift gate test
// kept them in sync. With this tool, the markdown doc is the
// single source of truth and `signatures.go` only carries the
// init logic + a tiny hand-maintained list of internal `_rad_*`
// signatures that have no public docs.
//
// Pipeline:
//
//	docs/funcs/*.md   ── source of truth
//	      │
//	      ▼ gen-funcs-sigs  (this tool)
//	rts/signatures_gen.go  ── generated, checked into git
//	      │
//	      ▼ rts.init  (at runtime)
//	parses each signature string into a Typing
//
// Usage:
//
//	go run ./tools/gen-funcs-sigs
//
// Defaults assume invocation from the repo root. Pass `-source`
// and `-out` to override.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/amterp/rad/rts"
)

const header = `// Code generated by tools/gen-funcs-sigs. DO NOT EDIT.
//
// Source of truth: docs/funcs/*.md (the ` + "`## Signature`" + ` section of
// each file). Regenerate with ` + "`go generate ./rts`" + `.

package rts

// publicSignatures is the sorted list of public builtin signature
// strings, harvested from docs/funcs/*.md. The runtime's init in
// signatures.go parses each into a TypingFnT and registers it in
// FnSignaturesByName.
var publicSignatures = []string{
`

const footer = `}
`

func main() {
	var (
		source = flag.String("source", "docs/funcs", "path to the source docs/funcs/ directory")
		out    = flag.String("out", "rts/signatures_gen.go", "path to write the generated signatures file")
	)
	flag.Parse()

	if err := run(*source, *out); err != nil {
		fmt.Fprintf(os.Stderr, "gen-funcs-sigs: %v\n", err)
		os.Exit(1)
	}
}

func run(source, out string) error {
	entries, err := os.ReadDir(source)
	if err != nil {
		return fmt.Errorf("read %s: %w", source, err)
	}

	var sigs []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".md") {
			continue
		}
		stem := strings.TrimSuffix(name, ".md")
		if !rts.IsValidFuncDocStem(stem) {
			continue // README.md, contributor notes, etc.
		}
		// Internal `_rad_*` builtins are hand-maintained in
		// rts/signatures.go's internalSignatures and explicitly
		// excluded from the public surface. The README directs
		// contributors to put any internal docs under
		// docs/funcs/internal/ (a subdirectory; skipped by IsDir
		// above). If one lands at the root anyway, fail loudly
		// rather than silently leaking it into publicSignatures
		// where it would collide with internalSignatures at init
		// time.
		if strings.HasPrefix(stem, "_rad_") {
			return fmt.Errorf("%s: `_rad_*` docs belong under docs/funcs/internal/, not at the root", name)
		}
		body, err := os.ReadFile(filepath.Join(source, name))
		if err != nil {
			return fmt.Errorf("read %s: %w", name, err)
		}
		doc, err := rts.ParseFuncDoc(stem, string(body))
		if err != nil {
			return fmt.Errorf("parse %s: %w", name, err)
		}
		if doc.Signature == "" {
			return fmt.Errorf("%s: empty signature", name)
		}
		sigs = append(sigs, doc.Signature)
	}

	if len(sigs) == 0 {
		return fmt.Errorf("no signatures found under %s", source)
	}
	sort.Strings(sigs)

	var b bytes.Buffer
	b.WriteString(header)
	for _, s := range sigs {
		// Raw string literals (backticks) preserve everything but
		// can't contain a backtick. None of Rad's signatures do
		// today, but guard anyway and fall back to a quoted
		// literal if needed.
		if strings.ContainsRune(s, '`') {
			b.WriteString("\t" + strconvQuote(s) + ",\n")
		} else {
			b.WriteString("\t`" + s + "`,\n")
		}
	}
	b.WriteString(footer)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(out), err)
	}
	if existing, err := os.ReadFile(out); err == nil && bytes.Equal(existing, formatted) {
		fmt.Printf("gen-funcs-sigs: %s up to date (%d signatures)\n", out, len(sigs))
		return nil
	}
	if err := os.WriteFile(out, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", out, err)
	}
	fmt.Printf("gen-funcs-sigs: wrote %d signatures to %s\n", len(sigs), out)
	return nil
}

// strconvQuote is a stripped-down strconv.Quote for the rare case
// where a signature contains a backtick. Kept local so this binary
// doesn't grow imports for a path we don't expect to hit.
func strconvQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

