// gen-errors-page regenerates the public-facing errors reference at
// `docs-web/docs/reference/errors.md` from the canonical per-code
// markdown files under `core/error_docs/*.md` (the same files that
// power `rad docs <code>`).
//
// The pipeline:
//
//	core/error_docs/<code>.md   ── source of truth (per-code)
//	      │
//	      ▼ gen-errors-page (this binary)
//	docs-web/docs/reference/errors.md   ── derived aggregate
//
// The hand-written preamble lives in `tools/gen-errors-page/preamble.md`
// and is prepended verbatim.
//
// Layout:
//   - `## <Band>` section per error-code band (1xxxx Syntax, 2xxxx
//     Runtime, 3xxxx Type, 4xxxx Validation/Lint), in numeric order.
//   - Within a band, each code's doc in numeric order, with its
//     headings demoted two levels so the per-file `# RAD10001: Title`
//     becomes a `###` entry under the band's `##`.
//
// Usage:
//
//	go run ./tools/gen-errors-page
//
// Defaults assume invocation from the repo root. Pass `-source`
// and `-out` to override.
package main

import (
	_ "embed"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

//go:embed preamble.md
var preamble string

// bands maps code/10000 to the band name used as the section header.
// Names mirror the band comment in rts/rl/errors.go.
var bands = map[int]string{
	1: "Syntax Errors (RAD1xxxx)",
	2: "Runtime Errors (RAD2xxxx)",
	3: "Type Errors (RAD3xxxx)",
	4: "Validation & Lint Errors (RAD4xxxx)",
}

var errorDocFile = regexp.MustCompile(`^(\d{5})\.md$`)

func main() {
	var (
		source = flag.String("source", "core/error_docs", "path to the source error_docs directory")
		out    = flag.String("out", "docs-web/docs/reference/errors.md", "path to write the aggregated errors reference")
		dryRun = flag.Bool("dry-run", false, "print the generated output to stdout instead of writing")
	)
	flag.Parse()

	if err := run(*source, *out, *dryRun); err != nil {
		fmt.Fprintf(os.Stderr, "gen-errors-page: %v\n", err)
		os.Exit(1)
	}
}

func run(source, out string, dryRun bool) error {
	codes, err := loadErrorDocs(source)
	if err != nil {
		return err
	}
	if len(codes) == 0 {
		return fmt.Errorf("no error docs found under %s", source)
	}

	combined := "<!-- THIS FILE IS GENERATED by tools/gen-errors-page from core/error_docs/. DO NOT EDIT. -->\n\n" +
		preamble + render(codes)

	if dryRun {
		fmt.Print(combined)
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(out), err)
	}
	if err := os.WriteFile(out, []byte(combined), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", out, err)
	}
	fmt.Printf("gen-errors-page: wrote %d error codes to %s\n", len(codes), out)
	return nil
}

type errorDoc struct {
	code int
	body string
}

func loadErrorDocs(dir string) ([]errorDoc, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", dir, err)
	}
	var docs []errorDoc
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		m := errorDocFile.FindStringSubmatch(e.Name())
		if m == nil {
			continue // README.md etc.
		}
		code, err := strconv.Atoi(m[1])
		if err != nil {
			return nil, fmt.Errorf("parse code from %s: %w", e.Name(), err)
		}
		body, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", e.Name(), err)
		}
		docs = append(docs, errorDoc{code: code, body: string(body)})
	}
	sort.Slice(docs, func(i, j int) bool { return docs[i].code < docs[j].code })
	return docs, nil
}

func render(docs []errorDoc) string {
	var b strings.Builder
	currentBand := 0
	for _, d := range docs {
		band := d.code / 10000
		if band != currentBand {
			currentBand = band
			name, ok := bands[band]
			if !ok {
				name = fmt.Sprintf("RAD%dxxxx", band)
			}
			b.WriteString("\n## ")
			b.WriteString(name)
			b.WriteString("\n")
		}
		b.WriteString("\n")
		b.WriteString(strings.TrimRight(demoteHeadings(d.body), "\n"))
		b.WriteString("\n")
	}
	return b.String()
}

// demoteHeadings shifts every markdown heading down two levels so a
// per-file document nests under the aggregate page's band sections.
// Fence-aware: a `#` line inside a code block is content, not a
// heading (e.g. shebangs in rad examples).
func demoteHeadings(body string) string {
	lines := strings.Split(body, "\n")
	inFence := false
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "```") {
			inFence = !inFence
			continue
		}
		if !inFence && strings.HasPrefix(line, "#") {
			lines[i] = "##" + line
		}
	}
	return strings.Join(lines, "\n")
}
