package core

import (
	"embed"
	"encoding/json"
	"regexp"
	"strings"
	"sync"

	"github.com/amterp/rad/rts"
)

// embedded_docs/ is generated by tools/gen-docs-embed from the
// canonical docs in docs-web/docs/ (driven by the mkdocs.yml nav).
// It's the data behind `rad docs`, so the docs a binary serves
// always match its own version. See tools/gen-docs-embed for the
// pipeline and core/testing for the drift gate.
//
//go:embed embedded_docs/*
var docFiles embed.FS

// DocPage is one entry in the embedded docs manifest.
type DocPage struct {
	Slug    string   `json:"slug"`
	Section string   `json:"section"`
	Title   string   `json:"title"`
	H2s     []string `json:"h2s"`
	// InAll marks a page as part of `rad docs all`. Every embedded page
	// is addressable by slug; only these join the bulk dump. Migration
	// guides ship without it - see fullCorpusSections in
	// tools/gen-docs-embed.
	InAll bool `json:"in_all"`
}

var (
	docsManifest     []DocPage
	docsFuncs        []string
	docsManifestOnce sync.Once
)

func loadDocsManifest() {
	data, err := docFiles.ReadFile("embedded_docs/manifest.json")
	if err != nil {
		return
	}
	var m struct {
		Pages []DocPage `json:"pages"`
		Funcs []string  `json:"funcs"`
	}
	if err := json.Unmarshal(data, &m); err != nil {
		return
	}
	docsManifest = m.Pages
	docsFuncs = m.Funcs
}

// GetDocsManifest returns the embedded doc pages in nav order.
func GetDocsManifest() []DocPage {
	docsManifestOnce.Do(loadDocsManifest)
	return docsManifest
}

// GetDocFuncs returns the names of every built-in with an embedded
// per-function doc page (i.e. every `rad docs <name>` that resolves).
func GetDocFuncs() []string {
	docsManifestOnce.Do(loadDocsManifest)
	return docsFuncs
}

// GetDocPage returns the raw markdown for one page slug (e.g.
// "guide/basics"), or false if no such page is embedded.
func GetDocPage(slug string) (string, bool) {
	content, err := docFiles.ReadFile("embedded_docs/" + slug + ".md")
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(rts.StripGeneratedBanner(string(content))), true
}

// errorCodePattern matches a `rad docs` topic that's really an error
// code: an optional case-insensitive "RAD" prefix plus the numeric
// part (e.g. "RAD10001", "10001"). Page slugs always contain a "/"
// or letters, so they never collide with this.
var errorCodePattern = regexp.MustCompile(`(?i)^(?:rad)?(\d{4,6})$`)

// GetFuncDoc returns the per-function doc page for a built-in (e.g.
// "len"), or false if no such function is documented.
func GetFuncDoc(name string) (string, bool) {
	content, err := docFiles.ReadFile("embedded_docs/funcs/" + name + ".md")
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(rts.StripGeneratedBanner(string(content))), true
}

// sectionIndexLeaf is the slug leaf marking a section's landing page
// (e.g. "migrations/index"). Such a page is addressable by its section
// name alone, and its website URL is the directory, not the slug.
const sectionIndexLeaf = "index"

// GetDocTopic resolves a `rad docs <topic>` argument to raw markdown.
// It's the single entry point, accepting (in precedence order) error
// codes, built-in function names, section names, and page slugs:
// `rad docs RAD10001` explains an error, `rad docs len` prints a
// function's doc, `rad docs migrations` prints a section's index, and
// `rad docs guide/basics` prints a page. Error codes are digits and
// slugs contain a "/", so the only namespace that can collide is
// function names against section names - gen-docs-embed rejects that
// at build time. Returns false if nothing matches.
func GetDocTopic(topic string) (string, bool) {
	if m := errorCodePattern.FindStringSubmatch(topic); m != nil {
		if doc := GetErrorDoc(m[1]); doc != "" {
			return doc, true
		}
		return "", false
	}
	if !strings.Contains(topic, "/") {
		if doc, ok := GetFuncDoc(topic); ok {
			return doc, true
		}
		// A section name alone means its index page, so `rad docs
		// migrations` works without knowing the slug is
		// migrations/index. gen-docs-embed refuses a built-in whose
		// name would shadow one of these.
		if doc, ok := GetDocPage(topic + "/" + sectionIndexLeaf); ok {
			return doc, true
		}
	}
	return GetDocPage(topic)
}

// DocTopicSlug reports the page slug a `rad docs` topic addresses,
// resolving the bare-section shorthand. Empty if the topic isn't a page.
func DocTopicSlug(topic string) string {
	if _, ok := GetDocPage(topic); ok {
		return topic
	}
	if !strings.Contains(topic, "/") {
		alias := topic + "/" + sectionIndexLeaf
		if _, ok := GetDocPage(alias); ok {
			return alias
		}
	}
	return ""
}

// docsSiteURL is the root of the documentation website. `--web` maps a
// topic onto it, and `rad docs` and the site are generated from the
// same sources, so the two stay addressable the same way.
const docsSiteURL = "https://amterp.dev/rad"

// GetDocURL maps a `rad docs` topic to its page on the documentation
// website, or false if the topic resolves to nothing. Mirrors
// GetDocTopic's precedence: error codes, then built-ins, then pages.
func GetDocURL(topic string) (string, bool) {
	// No topic is the index, and `all` has no page of its own; both
	// land on the site home.
	if topic == "" || topic == "all" {
		return docsSiteURL, true
	}
	if m := errorCodePattern.FindStringSubmatch(topic); m != nil {
		if doc := GetErrorDoc(m[1]); doc != "" {
			// Error docs aren't their own pages on the site; they're
			// banded into the errors reference.
			return docsSiteURL + "/reference/errors", true
		}
		return "", false
	}
	if !strings.Contains(topic, "/") {
		if _, ok := GetFuncDoc(topic); ok {
			return docsSiteURL + "/reference/functions#" + topic, true
		}
	}
	slug := DocTopicSlug(topic)
	if slug == "" {
		return "", false
	}
	// mkdocs serves a section index at its directory, so the "/index"
	// the slug carries would 404.
	return docsSiteURL + "/" + strings.TrimSuffix(slug, "/"+sectionIndexLeaf), true
}

// BuildDocsTOC renders the topic index: sections, titles, the
// command to print each page, and an H2 preview. It's the
// `rad docs` (no-arg) listing and the header of `rad docs all`.
func BuildDocsTOC() string {
	var b strings.Builder
	b.WriteString("# Rad Documentation\n\n")
	b.WriteString("Run `rad docs <topic>` to print a page, `rad docs <function>` for a built-in ")
	b.WriteString("(e.g. `rad docs len`), `rad docs all` for the full corpus, ")
	b.WriteString("or `rad docs RAD<code>` (e.g. `rad docs RAD10001`) to explain an error code.\n")

	section := ""
	for _, p := range GetDocsManifest() {
		if p.Section != section {
			section = p.Section
			b.WriteString("\n## ")
			b.WriteString(section)
			b.WriteString("\n\n")
		}
		b.WriteString("- **")
		b.WriteString(p.Title)
		b.WriteString("** (`rad docs ")
		b.WriteString(strings.TrimSuffix(p.Slug, "/"+sectionIndexLeaf))
		b.WriteString("`)")
		if len(p.H2s) > 0 {
			b.WriteString(": ")
			b.WriteString(strings.Join(p.H2s, ", "))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// BuildDocsFull renders the bulk corpus: the TOC followed by the
// content of every page marked InAll, H1-wrapped and separated by
// horizontal rules. This mirrors llms-full.txt so `rad docs all` is the
// "load everything" mode agents reach for. Migration guides are listed
// in the TOC but left out of the dump - they teach syntax that no
// longer works.
func BuildDocsFull() string {
	var b strings.Builder
	b.WriteString(BuildDocsTOC())
	for _, p := range GetDocsManifest() {
		if !p.InAll {
			continue
		}
		body, ok := GetDocPage(p.Slug)
		if !ok {
			continue
		}
		b.WriteString("\n\n---\n\n")
		if strings.HasPrefix(body, "# ") {
			b.WriteString(body)
		} else {
			b.WriteString("# ")
			b.WriteString(p.Title)
			b.WriteString("\n\n")
			b.WriteString(body)
		}
	}
	b.WriteString("\n")
	return b.String()
}
