package core

import (
	"embed"
	"encoding/json"
	"regexp"
	"strings"
	"sync"
)

// embedded_docs/ is generated by tools/gen-docs-embed from the
// canonical docs in docs-web/docs/ (driven by the mkdocs.yml nav).
// It's the data behind `rad docs`, so the docs a binary serves
// always match its own version. See tools/gen-docs-embed for the
// pipeline and core/testing for the drift gate.
//
//go:embed embedded_docs/*
var docFiles embed.FS

// DocPage is one entry in the embedded docs manifest.
type DocPage struct {
	Slug    string   `json:"slug"`
	Section string   `json:"section"`
	Title   string   `json:"title"`
	H2s     []string `json:"h2s"`
}

var (
	docsManifest     []DocPage
	docsManifestOnce sync.Once
)

func loadDocsManifest() {
	data, err := docFiles.ReadFile("embedded_docs/manifest.json")
	if err != nil {
		return
	}
	var m struct {
		Pages []DocPage `json:"pages"`
	}
	if err := json.Unmarshal(data, &m); err != nil {
		return
	}
	docsManifest = m.Pages
}

// GetDocsManifest returns the embedded doc pages in nav order.
func GetDocsManifest() []DocPage {
	docsManifestOnce.Do(loadDocsManifest)
	return docsManifest
}

// GetDocSlugs returns every page slug, in nav order. Used to
// validate `rad docs <topic>` and to list valid topics on a miss.
func GetDocSlugs() []string {
	pages := GetDocsManifest()
	slugs := make([]string, 0, len(pages))
	for _, p := range pages {
		slugs = append(slugs, p.Slug)
	}
	return slugs
}

// GetDocPage returns the raw markdown for one page slug (e.g.
// "guide/basics"), or false if no such page is embedded.
func GetDocPage(slug string) (string, bool) {
	content, err := docFiles.ReadFile("embedded_docs/" + slug + ".md")
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(string(content)), true
}

// errorCodePattern matches a `rad docs` topic that's really an error
// code: an optional case-insensitive "RAD" prefix plus the numeric
// part (e.g. "RAD10001", "10001"). Page slugs always contain a "/"
// or letters, so they never collide with this.
var errorCodePattern = regexp.MustCompile(`(?i)^(?:rad)?(\d{4,6})$`)

// GetDocTopic resolves a `rad docs <topic>` argument to raw markdown.
// It accepts both page slugs and error codes, so `rad docs` is the
// single entry point: `rad docs guide/basics` prints a page, while
// `rad docs RAD10001` prints that error's doc (the old `rad explain`
// behavior). Returns false if the topic matches neither.
func GetDocTopic(topic string) (string, bool) {
	if m := errorCodePattern.FindStringSubmatch(topic); m != nil {
		if doc := GetErrorDoc(m[1]); doc != "" {
			return doc, true
		}
		return "", false
	}
	return GetDocPage(topic)
}

// BuildDocsTOC renders the topic index: sections, titles, the
// command to print each page, and an H2 preview. It's the
// `rad docs` (no-arg) listing and the header of `rad docs all`.
func BuildDocsTOC() string {
	var b strings.Builder
	b.WriteString("# Rad Documentation\n\n")
	b.WriteString("Run `rad docs <topic>` to print a page, `rad docs all` for the full corpus, ")
	b.WriteString("or `rad docs RAD<code>` (e.g. `rad docs RAD10001`) to explain an error code.\n")

	section := ""
	for _, p := range GetDocsManifest() {
		if p.Section != section {
			section = p.Section
			b.WriteString("\n## ")
			b.WriteString(section)
			b.WriteString("\n\n")
		}
		b.WriteString("- **")
		b.WriteString(p.Title)
		b.WriteString("** (`rad docs ")
		b.WriteString(p.Slug)
		b.WriteString("`)")
		if len(p.H2s) > 0 {
			b.WriteString(": ")
			b.WriteString(strings.Join(p.H2s, ", "))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// BuildDocsFull renders the entire embedded corpus: the TOC followed
// by every page's content, H1-wrapped and separated by horizontal
// rules. This mirrors llms-full.txt so `rad docs all` is the
// "load everything" mode agents reach for.
func BuildDocsFull() string {
	var b strings.Builder
	b.WriteString(BuildDocsTOC())
	for _, p := range GetDocsManifest() {
		body, ok := GetDocPage(p.Slug)
		if !ok {
			continue
		}
		b.WriteString("\n\n---\n\n")
		if strings.HasPrefix(body, "# ") {
			b.WriteString(body)
		} else {
			b.WriteString("# ")
			b.WriteString(p.Title)
			b.WriteString("\n\n")
			b.WriteString(body)
		}
	}
	b.WriteString("\n")
	return b.String()
}
