package core

import (
	"embed"
	"encoding/json"
	"regexp"
	"strings"
	"sync"
)

// embedded_docs/ is generated by tools/gen-docs-embed from the
// canonical docs in docs-web/docs/ (driven by the mkdocs.yml nav).
// It's the data behind `rad docs`, so the docs a binary serves
// always match its own version. See tools/gen-docs-embed for the
// pipeline and core/testing for the drift gate.
//
//go:embed embedded_docs/*
var docFiles embed.FS

// DocPage is one entry in the embedded docs manifest.
type DocPage struct {
	Slug    string   `json:"slug"`
	Section string   `json:"section"`
	Title   string   `json:"title"`
	H2s     []string `json:"h2s"`
}

var (
	docsManifest     []DocPage
	docsFuncs        []string
	docsManifestOnce sync.Once
)

func loadDocsManifest() {
	data, err := docFiles.ReadFile("embedded_docs/manifest.json")
	if err != nil {
		return
	}
	var m struct {
		Pages []DocPage `json:"pages"`
		Funcs []string  `json:"funcs"`
	}
	if err := json.Unmarshal(data, &m); err != nil {
		return
	}
	docsManifest = m.Pages
	docsFuncs = m.Funcs
}

// GetDocsManifest returns the embedded doc pages in nav order.
func GetDocsManifest() []DocPage {
	docsManifestOnce.Do(loadDocsManifest)
	return docsManifest
}

// GetDocFuncs returns the names of every built-in with an embedded
// per-function doc page (i.e. every `rad docs <name>` that resolves).
func GetDocFuncs() []string {
	docsManifestOnce.Do(loadDocsManifest)
	return docsFuncs
}

// GetDocSlugs returns every page slug, in nav order. Used to
// validate `rad docs <topic>` and to list valid topics on a miss.
func GetDocSlugs() []string {
	pages := GetDocsManifest()
	slugs := make([]string, 0, len(pages))
	for _, p := range pages {
		slugs = append(slugs, p.Slug)
	}
	return slugs
}

// GetDocPage returns the raw markdown for one page slug (e.g.
// "guide/basics"), or false if no such page is embedded.
func GetDocPage(slug string) (string, bool) {
	content, err := docFiles.ReadFile("embedded_docs/" + slug + ".md")
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(string(content)), true
}

// errorCodePattern matches a `rad docs` topic that's really an error
// code: an optional case-insensitive "RAD" prefix plus the numeric
// part (e.g. "RAD10001", "10001"). Page slugs always contain a "/"
// or letters, so they never collide with this.
var errorCodePattern = regexp.MustCompile(`(?i)^(?:rad)?(\d{4,6})$`)

// GetFuncDoc returns the per-function doc page for a built-in (e.g.
// "len"), or false if no such function is documented.
func GetFuncDoc(name string) (string, bool) {
	content, err := docFiles.ReadFile("embedded_docs/funcs/" + name + ".md")
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(string(content)), true
}

// GetDocTopic resolves a `rad docs <topic>` argument to raw markdown.
// It's the single entry point, accepting (in precedence order) error
// codes, built-in function names, and page slugs: `rad docs RAD10001`
// explains an error, `rad docs len` prints a function's doc, and
// `rad docs guide/basics` prints a page. Precedence is unambiguous -
// error codes are digits, function names are bare identifiers, and
// page slugs always contain a "/". Returns false if nothing matches.
func GetDocTopic(topic string) (string, bool) {
	if m := errorCodePattern.FindStringSubmatch(topic); m != nil {
		if doc := GetErrorDoc(m[1]); doc != "" {
			return doc, true
		}
		return "", false
	}
	if !strings.Contains(topic, "/") {
		if doc, ok := GetFuncDoc(topic); ok {
			return doc, true
		}
	}
	return GetDocPage(topic)
}

// BuildDocsTOC renders the topic index: sections, titles, the
// command to print each page, and an H2 preview. It's the
// `rad docs` (no-arg) listing and the header of `rad docs all`.
func BuildDocsTOC() string {
	var b strings.Builder
	b.WriteString("# Rad Documentation\n\n")
	b.WriteString("Run `rad docs <topic>` to print a page, `rad docs <function>` for a built-in ")
	b.WriteString("(e.g. `rad docs len`), `rad docs all` for the full corpus, ")
	b.WriteString("or `rad docs RAD<code>` (e.g. `rad docs RAD10001`) to explain an error code.\n")

	section := ""
	for _, p := range GetDocsManifest() {
		if p.Section != section {
			section = p.Section
			b.WriteString("\n## ")
			b.WriteString(section)
			b.WriteString("\n\n")
		}
		b.WriteString("- **")
		b.WriteString(p.Title)
		b.WriteString("** (`rad docs ")
		b.WriteString(p.Slug)
		b.WriteString("`)")
		if len(p.H2s) > 0 {
			b.WriteString(": ")
			b.WriteString(strings.Join(p.H2s, ", "))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// BuildDocsFull renders the entire embedded corpus: the TOC followed
// by every page's content, H1-wrapped and separated by horizontal
// rules. This mirrors llms-full.txt so `rad docs all` is the
// "load everything" mode agents reach for.
func BuildDocsFull() string {
	var b strings.Builder
	b.WriteString(BuildDocsTOC())
	for _, p := range GetDocsManifest() {
		body, ok := GetDocPage(p.Slug)
		if !ok {
			continue
		}
		b.WriteString("\n\n---\n\n")
		if strings.HasPrefix(body, "# ") {
			b.WriteString(body)
		} else {
			b.WriteString("# ")
			b.WriteString(p.Title)
			b.WriteString("\n\n")
			b.WriteString(body)
		}
	}
	b.WriteString("\n")
	return b.String()
}
