package testing

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/amterp/rad/core"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var embeddedDocSections = map[string]bool{"Guide": true, "Reference": true, "Examples": true, "Migrations": true}

// TestDocsManifestConsistency verifies the embedded docs manifest and
// the embedded .md tree are in lockstep: every manifest page has a
// readable file, every file is in the manifest, and sections are the
// expected set. The nav->embedded drift (a new doc page that wasn't
// regenerated) is gated separately by `make verify-generated`, which
// re-runs gen-docs-embed and diffs.
func TestDocsManifestConsistency(t *testing.T) {
	manifest := core.GetDocsManifest()
	require.NotEmpty(t, manifest, "embedded docs manifest is empty - did gen-docs-embed run?")

	manifestSlugs := map[string]bool{}
	for _, p := range manifest {
		assert.Truef(t, embeddedDocSections[p.Section], "unexpected section %q for %q", p.Section, p.Slug)
		assert.NotEmptyf(t, p.Title, "page %q has no title", p.Slug)
		content, ok := core.GetDocPage(p.Slug)
		assert.Truef(t, ok, "manifest page %q has no embedded file", p.Slug)
		assert.NotEmptyf(t, content, "manifest page %q is empty", p.Slug)
		manifestSlugs[p.Slug] = true
	}

	// Per-function pages are addressable by bare name; on disk they
	// live under funcs/<name>.md (slug "funcs/<name>").
	funcs := core.GetDocFuncs()
	require.NotEmpty(t, funcs, "manifest funcs list is empty - did gen-docs-embed run?")
	for _, name := range funcs {
		content, ok := core.GetFuncDoc(name)
		assert.Truef(t, ok, "manifest func %q has no embedded file", name)
		assert.NotEmptyf(t, content, "manifest func %q is empty", name)
		manifestSlugs["funcs/"+name] = true
	}

	// Every embedded .md on disk must be in the manifest (no orphans
	// left behind by a stale generation).
	root := "../embedded_docs"
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}
		rel, _ := filepath.Rel(root, path)
		slug := strings.TrimSuffix(filepath.ToSlash(rel), ".md")
		assert.Truef(t, manifestSlugs[slug], "embedded file %q is not in the manifest", slug)
		return nil
	})
	require.NoError(t, err)

	// Sanity: the core reference + entry pages are always present.
	for _, slug := range []string{"reference/syntax", "reference/functions", "reference/errors", "guide/basics"} {
		_, ok := core.GetDocPage(slug)
		assert.Truef(t, ok, "expected core page %q to be embedded", slug)
	}
}

// TestEmbeddedCorpusIsClean guards that the embedded corpus carries no
// mkdocs-only markup or authoring comments - those don't survive the
// terminal renderer and used to leak as literal noise (and into piped
// LLM context). gen-docs-embed normalizes them through tools/docir; if
// this regresses, the source authored a construct docir doesn't handle.
func TestEmbeddedCorpusIsClean(t *testing.T) {
	banned := map[string]string{
		"[//]:":  "authoring comment",
		"!!!":    "admonition",
		`=== "`:  "content tab",
		"<div":   "raw HTML wrapper",
		"</div>": "raw HTML wrapper",
		"<!--":   "raw HTML comment",
	}
	root := "../embedded_docs"
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}
		content, readErr := os.ReadFile(path)
		require.NoError(t, readErr)
		rel, _ := filepath.Rel(root, path)
		lines := strings.Split(string(content), "\n")
		// Line 1 is the generated banner (stripped before serve); every
		// other line must be clean - including of stray HTML comments.
		if len(lines) > 0 && strings.HasPrefix(lines[0], "<!-- GENERATED by tools/") {
			lines = lines[1:]
		}
		for _, line := range lines {
			trimmed := strings.TrimSpace(line)
			for marker, desc := range banned {
				assert.Falsef(t, strings.HasPrefix(trimmed, marker),
					"%s: %s leaked into embedded corpus: %q", rel, desc, line)
			}
		}
		return nil
	})
	require.NoError(t, err)
}

// TestDocsTopicResolution verifies `rad docs <topic>` routing: error
// codes (with or without the RAD prefix) resolve to error docs, page
// slugs resolve to pages, and unknown topics miss. This is what makes
// `rad docs` the single entry point, error codes included.
func TestDocsTopicResolution(t *testing.T) {
	// Error codes route to error docs (the old `rad explain` behavior).
	doc, ok := core.GetDocTopic("RAD10001")
	require.True(t, ok, "RAD10001 should resolve")
	assert.Contains(t, doc, "RAD10001")

	docNoPrefix, ok := core.GetDocTopic("10001")
	require.True(t, ok, "10001 (no prefix) should resolve")
	assert.Equal(t, doc, docNoPrefix, "prefixed and unprefixed codes resolve identically")

	// Page slugs route to pages.
	_, ok = core.GetDocTopic("reference/functions")
	assert.True(t, ok, "reference/functions should resolve")

	// Bare function names route to per-function pages.
	fnDoc, ok := core.GetDocTopic("len")
	require.True(t, ok, "rad docs len should resolve to a function page")
	assert.Contains(t, fnDoc, "len", "function page should mention the function")

	// A bare section name is shorthand for its index page, so users
	// don't have to know the slug carries "/index".
	for _, section := range []string{"migrations", "examples"} {
		viaAlias, ok := core.GetDocTopic(section)
		require.Truef(t, ok, "rad docs %s should resolve to the section index", section)
		viaSlug, ok := core.GetDocTopic(section + "/index")
		require.True(t, ok)
		assert.Equal(t, viaSlug, viaAlias, "the alias and the slug serve the same page")
	}

	// Unknown topics miss.
	_, ok = core.GetDocTopic("nonsense")
	assert.False(t, ok, "unknown topic should not resolve")
	_, ok = core.GetDocTopic("RAD99999")
	assert.False(t, ok, "unknown error code should not resolve")
}

// TestDocsURLMapping covers `rad docs <topic> --web`. The mapping used
// to live in the Rad script untested, where an unknown topic silently
// opened the site root and a section index produced a 404 URL (mkdocs
// serves those at the directory).
func TestDocsURLMapping(t *testing.T) {
	for _, tc := range []struct {
		topic string
		want  string
	}{
		{"", "https://amterp.dev/rad"},
		{"all", "https://amterp.dev/rad"},
		{"guide/basics", "https://amterp.dev/rad/guide/basics"},
		{"migrations/v0.12", "https://amterp.dev/rad/migrations/v0.12"},
		{"migrations", "https://amterp.dev/rad/migrations"},
		{"examples", "https://amterp.dev/rad/examples"},
		{"examples/index", "https://amterp.dev/rad/examples"},
		{"len", "https://amterp.dev/rad/reference/functions#len"},
		{"RAD10001", "https://amterp.dev/rad/reference/errors"},
		{"10001", "https://amterp.dev/rad/reference/errors"},
	} {
		url, ok := core.GetDocURL(tc.topic)
		require.Truef(t, ok, "%q should map to a URL", tc.topic)
		assert.Equalf(t, tc.want, url, "URL for %q", tc.topic)
	}

	for _, topic := range []string{"nonsense", "RAD99999", "guide/nope"} {
		_, ok := core.GetDocURL(topic)
		assert.Falsef(t, ok, "%q should not map to a URL", topic)
	}
}

// TestDocsFullCoversWholeCorpus verifies `rad docs all` inlines every
// embedded page (matching llms-full.txt) and leads with the TOC.
func TestDocsFullCoversWholeCorpus(t *testing.T) {
	toc := core.BuildDocsTOC()
	full := core.BuildDocsFull()

	for _, section := range []string{"## Guide", "## Reference", "## Examples", "## Migrations"} {
		assert.Contains(t, toc, section, "TOC should list every embedded section")
	}
	assert.Contains(t, toc, "rad docs guide/basics", "TOC should show the per-page command")
	// Section index pages advertise the shorthand, not the raw slug.
	assert.Contains(t, toc, "rad docs migrations`", "TOC should offer the section shorthand")
	assert.NotContains(t, toc, "rad docs migrations/index", "TOC should not show the /index slug")

	// Migration guides are addressable and listed, but stay out of the
	// bulk dump - they demonstrate syntax that no longer works, which is
	// the last thing an LLM loading the corpus should absorb.
	assert.Contains(t, toc, "rad docs migrations/v0.12", "migrations belong in the TOC")
	assert.NotContains(t, full, "Migrating to Rad v0.12", "migrations must stay out of `rad docs all`")
	_, ok := core.GetDocTopic("migrations/v0.12")
	assert.True(t, ok, "migrations are still addressable by slug")

	assert.True(t, strings.HasPrefix(full, toc), "full corpus should lead with the TOC")
	// The corpus is the TOC plus every page's inlined body, so it dwarfs
	// the index alone - cheap proof that content (not just the TOC) shipped.
	assert.Greater(t, len(full), 2*len(toc), "full corpus should inline page bodies, not just the TOC")
}
