package rts

import (
	"fmt"
	"strings"
)

// generatedBannerPrefix is the stable head of every generated-doc
// banner. Strippers match on this so one helper handles every
// generator's banner regardless of the trailing source/regen text.
const generatedBannerPrefix = "<!-- GENERATED by tools/"

// GeneratedBanner builds the one-line HTML comment prepended to every
// embedded markdown doc (the core/embedded_docs/ corpus and the
// rts/embedded_funcs/ mirror). It makes a file's generated nature
// obvious when opened locally - which .gitattributes (GitHub diffs
// only) can't do - while StripGeneratedBanner keeps it out of served
// output. `by` is the generator (e.g. "tools/gen-docs-embed"); `from`
// is the source of truth it derives from.
func GeneratedBanner(by, from string) string {
	return fmt.Sprintf("<!-- GENERATED by %s from %s. DO NOT EDIT. Run: make generate -->", by, from)
}

// StripGeneratedBanner drops a leading GeneratedBanner line (and its
// single trailing newline), returning the remainder verbatim. It does
// not trim further, so an embedded_funcs file round-trips to its source
// byte-for-byte after stripping. Input without the banner is returned
// unchanged.
func StripGeneratedBanner(s string) string {
	if !strings.HasPrefix(s, generatedBannerPrefix) {
		return s
	}
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[i+1:]
	}
	return ""
}
