# GitHub Actions workflow for releasing Rad binaries
# Uses goreleaser-cross Docker image for CGO cross-compilation
# Publishes binaries for Linux, macOS, and Windows on multiple architectures

name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross:v1.21.5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global --add safe.directory /__w/rad/rad

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}